### ISSUE TITLE
Ways to optimize python-animeface?

### ISSUE THREAD

**Issue by kir12** [nya3jp/python-animeface#2]
I'm implementing `python-animeface` as part of a [larger project](https://gitlab.com/asi14/4k-pixellate) involving anime characters' faces. Insofar, `python-animeface`'s algorithm has worked fairly well, but some images haven't worked as well. (e.g. [this](https://en.touhouwiki.net/wiki/File:Th14Marisa.png) photo) It might very well be something wrong with my implementation of `anime-face`, but any chance you know of ways to optimize `python-animeface`?

**Comment by nya3jp** [comment]
Unfortunately, there's no easy way to optimize the model.

The original author of the library has [a page](http://anime.udp.jp/imager-animeface.html) describing how to train models, so it's technically possible to create models by yourself. But you'll need to implement a training code by your own (it's not published by the author) and also you'll need a dataset of anime character faces with region annotations.
